[package]
name = "async-compression"
version = "0.3.5"
authors = ["Wim Looman <wim@nemo157.com>", "Allen Bui <fairingrey@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["compression", "gzip", "zstd", "brotli", "async"]
categories = ["compression", "asynchronous"]
repository = "https://github.com/Nemo157/async-compression"
description = """
Adaptors between compression crates and Rust's modern asynchronous IO types.
"""

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
# groups
default = []
all = ["all-implementations", "all-algorithms"]
all-implementations = ["futures-io", "stream", "tokio-02"]
all-algorithms = ["brotli", "bzip2", "deflate", "gzip", "lzma", "xz", "zlib", "zstd"]

# implementations
stream = ["bytes"]

# algorithms
deflate = ["flate2"]
gzip = ["flate2"]
lzma = ["xz2"]
xz = ["xz2"]
zlib = ["flate2"]
zstd = ["libzstd", "zstd-safe"]

# deprecated
futures-bufread = ["futures-io"]
futures-write = ["futures-io"]

[dependencies]
xz2 = { version = "0.1.6", optional = true }
brotli = { version = "3.3.0", optional = true }
bytes = { version = "0.5.0", optional = true }
bzip2 = { version = "0.4.1" , optional = true }
flate2 = { version = "1.0.11", optional = true }
futures-core = { version = "0.3.0", default-features = false }
futures-util = { version = "0.3.0", default-features = false }
futures-io = { version = "0.3.0", default-features = false, features = ["std"], optional = true }
pin-project-lite = "0.1.1"
libzstd = { package = "zstd", version = "0.5.0", optional = true, default-features = false }
zstd-safe = { version = "2.0.0", optional = true, default-features = false }
memchr = "2.2.1"
tokio-02 = { package = "tokio", version = "0.2.21", optional = true, default-features = false }
async-io-macros = { git = "https://github.com/Nemo157/async-io-macros", branch = "prīmum" }
pin-utils = "0.1.0"

[dev-dependencies]
proptest = "0.9.4"
proptest-derive = "0.1.2"
rand = "0.7.2"
futures = "0.3.5"
futures-test = "0.3.5"
ntest = "0.3.3"
timebomb = "0.1.2"
bytes = "0.5.0"
tokio-02 = { package = "tokio", version = "0.2.21", default-features = false, features = ["io-util", "stream"] }

[[test]]
name = "brotli"
required-features = ["brotli"]

[[test]]
name = "bzip2"
required-features = ["bzip2"]

[[test]]
name = "deflate"
required-features = ["deflate"]

[[test]]
name = "gzip"
required-features = ["gzip"]

[[test]]
name = "lzma"
required-features = ["lzma"]

[[test]]
name = "xz"
required-features = ["xz"]

[[test]]
name = "zlib"
required-features = ["zlib"]

[[test]]
name = "zstd"
required-features = ["zstd"]
